= A Duct Book
Max Ovsiankin <https://github.com/maxov>
:linkcss:
:toc: left

== About This Book
https://github.com/duct-framework/duct[duct] is a fantastic framework for building server-side applications in Clojure.
It is highly modular.
This is a huge advantage when it comes to application development, however,
it can give the framework a steep learning curve a steep learning curve.
Existing documentation is distributed over many sources, is at various levels of being up-to-date,
and in my opinion has inadequate depth,
so I have written this (short) book to serve as an in-depth guide to duct.

*Objectives for this book*: If you read the whole way through, you should have a good grasp on how duct works, as well as common libraries and usage patterns.
You should feel ready to build complex server-side applications with duct, while troubleshooting issues on your own (for the most part!).

*Prerequisites*: I assume you have basic knowledge of how to work with Clojure.
The https://clojure.org/guides/getting_started[Clojure documentation] has a great guide on installing and learning Clojure, as well as links to books and other resources.

=== Contributing

Contributions are very welcome! Please make PRs against the sources at https://github.com/maxov/duct-book[maxov/duct-book].

== Duct: the 10,000 foot view

== Get Help

There is an active and friendly `#duct` channel on the http://clojurians.net[Clojurians] Slack.
Feel free to pop in and ask questions!

== Prior Work
In this section, I list all relevant duct resources I could find.
I have many of them to thank for providing some of the information contained in this guide.

=== Documentation
* https://github.com/duct-framework/docs/blob/master/GUIDE.rst[duct docs - guide]
* duct wiki
** https://github.com/duct-framework/duct/wiki/Configuration[duct wiki - Configuration]
** https://github.com/duct-framework/duct/wiki/Getting-Started[duct wiki - Getting Started]
** https://github.com/duct-framework/duct/wiki/Boundaries[duct wiki - Boundaries]
** https://github.com/duct-framework/duct/wiki/Modules[duct wiki - Modules]
* https://github.com/weavejester/ataraxy[ataraxy - readme]

=== Blog Posts
* https://circleci.com/blog/build-a-clojure-web-app-using-duct/[CircleCi - Build a Clojure web app using Duct]
* https://grison.me/2018/06/15/duct-and-redis/[grison.me - Duct and Redis]
* weavejester's blog (the creator of Duct)
** https://www.booleanknot.com/blog/2017/05/09/advancing-duct.html[booleanknot - Advancing Duct]
** https://www.booleanknot.com/blog/2017/05/29/building-web-services-with-duct.html[booleanknot - Building Web Services with Duct]
* Flexiana Blog
** https://flexiana.com/2020/07/building-web-services-with-duct-1-part[flexiana - Building Web Services with Duct - Part 1]
** https://flexiana.com/2020/07/building-web-services-with-duct-2-part[flexiana - Building Web Services with Duct - Part 2]
** https://flexiana.com/2020/07/building-web-services-with-duct-3-part[flexiana - Building Web Services with Duct - Part 3]

=== Talks
* https://www.youtube.com/watch?v=IVnBW2mT7Po[James Reeves - Productive Duct]
